---
title: "Linear Regression"
author: "Yufan Luo"
date: "10/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(caret);library(lattice);library(ggplot2);library(dplyr);library(tidyr)
houses<-read.csv("C:/Users/luoyu/Desktop/COLUMBIA/Methods and Framework/4_linearregression/assignment/houses.csv")
```

## Split dataset
```{r}
set.seed(1031)
split=createDataPartition(houses$price,p=0.7,list=F,groups=100)
train=houses[split,]
test=houses[-split,]
mean(train$price)
mean(test$price)
```

## Know the dataset
```{r}
# outliers
train %>%
  select(id,price:sqft_lot,age)%>%
  gather(key=numericVariable,value=value,price:age)%>%
  ggplot(aes(x='',y=value))+
  geom_boxplot(outlier.color = 'red')+
  facet_wrap(~numericVariable,scales='free_y')
# Correlation
ggplot(data=train,aes(x=sqft_living,y=price))+geom_point()
```

## Linear Regression Model
```{r}
# Single variable model: Sqft_living
model1<-lm(price~sqft_living,data=train)
summary(model1)
pred=predict(model1)
sse=sum((pred-train$price)^2)
sst=sum((mean(train$price)-train$price)^2)
r2=1-sse/sst; r2
rmse=sqrt(mean((pred-train$price)^2));rmse
# Single variable model: Sqft_living
model2<-lm(price~waterfront,data=train)
summary(model2)
pred=predict(model2)
rmse2=sqrt(mean((pred-train$price)^2));rmse2
```

## Multivariable Model
```{r}
model3<-lm(price~sqft_living+waterfront,data=train);summary(model3)
model4<-lm(price~bedrooms+bathrooms+sqft_living+sqft_lot+floors+waterfront+view+condition+grade+age,data=train);summary(model4)
#In sample evaluation
pred=predict(model4)
rmse4=sqrt(mean((pred-train$price)^2));rmse4
#Out of sample evaluation
pred=predict(model4,newdata=test)
pred=predict(model4,newdata=test)
sse=sum((pred-test$price)^2)
sst=sum((mean(train$price)-test$price)^2)
r2=1-sse/sst;r2
rmse5=sqrt(mean((pred-test$price)^2));rmse5
```

## Standardized regression coefficients
```{r}
lm.beta(model4)#the larger the better
```




