---
title: "Simple Tree"
author: "Yufan Luo"
date: "10/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(rpart);library(rpart.plot);library(ggplot2)
wages<-read.csv("C:/Users/luoyu/Desktop/COLUMBIA/Methods and Framework/8_trees/TREE ASSIGNMENT/assignment7_wages.csv")
summary(wages)
wages = wages[wages$earn>0,] 
```

## Split data
```{r}
set.seed(100)
split = sample(1:nrow(wages), nrow(wages)*0.75)
train = wages[split,]
test = wages[-split,]
```

## Basic model and in sample evaluation
```{r}
model1<-lm(earn~.,data=train)
summary(model1)
pred<-predict(model1)
rmse1=sqrt(mean((pred-train$earn)^2));rmse1
```
## Improve the model
```{r}
# Variable: sex and in-sample evaluation
ggplot(data=train,aes(y=earn,x=sex,fill=factor(ed)))+ geom_bar(stat="summary",fun.y="mean",position="dodge")
ggplot(data=train,aes(y=earn,x=ed,color=sex))+  geom_smooth(method="lm",se=F,size=1.2)+  scale_x_continuous(breaks=c(seq(2,20,2)))+  scale_y_continuous(breaks=c(seq(0,100000,20000)))
model_sex_ed = lm(earn~sex + ed + sex*ed,data=train)
summary(model_sex_ed)
model2<-lm(earn~.+sex*ed,data=train)
pred<-predict(model2,data=train)
rmse2<-sqrt(mean((pred-train$earn)^2));rmse2
model3<-lm(earn~.+sex*ed+sex*age,data=train)
pred<-predict(model3,data=train)
rmse3<-sqrt(mean((pred-train$earn)^2));rmse3
model4<-lm(earn~.+sex*ed+sex*age+age*ed,data=train)
pred<-predict(model4,data=train)
rmse4<-sqrt(mean((pred-train$earn)^2));rmse4
model5 = lm(earn~(height+sex+race+ed+age)^2,data=train)
pred<-predict(model5,data=train)
rmse5<-sqrt(mean((pred-train$earn)^2));rmse5
summary(model1);summary(model5)
```
## Tree and In-sample evaluation
```{r}
tree1<-rpart(earn~.,data=train)
prp(tree1,digits=5)
pred=predict(tree1)
rmsetree1=sqrt(mean((pred-train$earn)^2))
rmsetree1
treeSimp1 = rpart(earn~.,data=train,control=rpart.control(minbucket=20))
prp(treeSimp1)
pred=predict(treeSimp1)
rmsetree2=sqrt(mean((pred-train$earn)^2))
rmsetree2
treeComplex1=rpart(earn~.,data=train,control=rpart.control(minbucket=5))
prp(treeComplex1,digits=5)
pred=predict(treeComplex1)
rmseComplex1<-sqrt(mean((pred-train$earn)^2))
rmseComplex1
treeComplex2=rpart(earn~.,data=train,control=rpart.control(minbucket=1))
prp(treeComplex2,digits=5)
pred=predict(treeComplex2)
rmseComplex2<-sqrt(mean((pred-train$earn)^2))
rmseComplex2
```
## out of sample evaluation
```{r}
pred = predict(model5, newdata=test)
rmse5_test = sqrt(mean((pred-test$earn)^2)); rmse5_test
pred = predict(tree1, newdata=test)
rmsetree1_test = sqrt(mean((pred-test$earn)^2)); rmsetree1_test
pred = predict(treeComplex2, newdata=test)
rmsetreeComplex2_test = sqrt(mean((pred-test$earn)^2)); rmsetreeComplex2_test
```

