---
title: "Advanced Tree"
author: "Yufan Luo"
date: "11/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r cars}
library(ISLR)
library(rpart)
library(caTools)
library(e1071)
library(lattice)
library(ggplot2)
library(caret)
library(ROCR)
library(gplots)
library(gbm)
library(randomForest)
head(OJ)
```

## Splitting data
```{r}
set.seed(1234)
split=sample.split(Y=OJ$Purchase,SplitRatio = 0.7)
train<-OJ[split,]
test<-OJ[!split,]
```

## Tree
```{r}
tree1<-rpart(Purchase~PriceCH+PriceMM+DiscCH+DiscMM+SpecialCH+SpecialMM+LoyalCH+PriceDiff+PctDiscMM+PctDiscCH,data=train,method='class')
pred<-predict(tree1,newdata=test)
ROCRpred<-prediction(pred[,2],test$Purchase)
as.numeric(performance(ROCRpred,'auc')@y.values)
set.seed(100)
trControl=trainControl(method='cv',number=10)
tuneGrid=expand.grid(.cp=seq(0,0.1,0.001))
trainCV=train(Purchase~PriceCH+PriceMM+DiscCH+DiscMM+SpecialCH+SpecialMM+LoyalCH+PriceDiff+PctDiscMM+PctDiscCH,data=train,method='rpart',trControl=trControl,tuneGrid=tuneGrid)
trainCV$bestTune
treeCV=rpart(Purchase~PriceCH+PriceMM+DiscCH+DiscMM+SpecialCH+SpecialMM+LoyalCH+PriceDiff+PctDiscMM+PctDiscCH,data=train,method='class',control=rpart.control(cp=trainCV$bestTune))
predCV=predict(treeCV,newdata=test)
predCV
ROCRpred<-prediction(predCV[,2],test$Purchase)
as.numeric(performance(ROCRpred,'auc')@y.values)
```
## Advanced trees
```{r}
#bag
set.seed(100)
bag=randomForest(Purchase~PriceCH+PriceMM+DiscCH+DiscMM+SpecialCH+SpecialMM+LoyalCH+PriceDiff+PctDiscMM+PctDiscCH,data=train,mtry=ncol(train)-1,ntree=1000)
predBag=predict(bag,newdata=test,type='prob')
ROCRpred=prediction(predBag[,2],test$Purchase)
round(as.numeric(performance(ROCRpred,'auc')@y.values),2)
#random forest
set.seed(100)
forest=randomForest(Purchase~PriceCH+PriceMM+DiscCH+DiscMM+SpecialCH+SpecialMM+LoyalCH+PriceDiff+PctDiscMM+PctDiscCH,data=train,ntree=1000)
predForest=predict(forest,newdata=test,type='prob')
ROCRpred=prediction(predForest[,2],test$Purchase)
round(as.numeric(performance(ROCRpred,'auc')@y.values),2)
train$Purchase2=as.numeric(train$Purchase)-1
test$Purchase2=as.numeric(test$Purchase)-1
#boost
set.seed(100)
boost=gbm(Purchase2~PriceCH+PriceMM+DiscCH+DiscMM+SpecialCH+SpecialMM+LoyalCH+PriceDiff+PctDiscMM+PctDiscCH,data=train,distribution='bernoulli',n.trees=1000,interaction.depth=1,shrinkage=0.04)
predBoostTrain=predict(boost,newdata=test,n.trees=1000,type='response')
ROCRpred=prediction(predBoostTrain,test$Purchase2)
round(as.numeric(performance(ROCRpred,'auc')@y.values),2)
```

